server:
  port: 9999

spring:
  application:
    name: gateway
  profiles:
    include:
      - core
      - @config.env@
  cloud:
    gateway:
      routes:
        - id: demo
          uri: http://httpbin.org
          predicates:
            - Host=**.httpbin.org
            - Path=/**
            - Header=X-Request-Id, \d+
        - id: demo1
          uri: http://localhost:8001
          predicates:
            - Path=/demo1/**
        - id: demo2
          uri: http://localhost:8002
          predicates:
            - Path=/demo2/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
