/*
 * This file is generated by jOOQ.
 */
package com.motorfu.gateway.jooq.tables.pojos;


import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 网关路由
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutesEntity implements Serializable {

    private static final long serialVersionUID = -726055689;

    private Long    id;
    private String  name;
    private String  uri;
    private String  filters;
    private String  predicates;
    private String  metadata;
    private Integer order;
    private Boolean deleted;
    private Long    created;
    private Long    lastModified;
    private String  createdBy;
    private String  lastModifiedBy;

    public RoutesEntity() {}

    public RoutesEntity(RoutesEntity value) {
        this.id = value.id;
        this.name = value.name;
        this.uri = value.uri;
        this.filters = value.filters;
        this.predicates = value.predicates;
        this.metadata = value.metadata;
        this.order = value.order;
        this.deleted = value.deleted;
        this.created = value.created;
        this.lastModified = value.lastModified;
        this.createdBy = value.createdBy;
        this.lastModifiedBy = value.lastModifiedBy;
    }

    public RoutesEntity(
        Long    id,
        String  name,
        String  uri,
        String  filters,
        String  predicates,
        String  metadata,
        Integer order,
        Boolean deleted,
        Long    created,
        Long    lastModified,
        String  createdBy,
        String  lastModifiedBy
    ) {
        this.id = id;
        this.name = name;
        this.uri = uri;
        this.filters = filters;
        this.predicates = predicates;
        this.metadata = metadata;
        this.order = order;
        this.deleted = deleted;
        this.created = created;
        this.lastModified = lastModified;
        this.createdBy = createdBy;
        this.lastModifiedBy = lastModifiedBy;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Size(max = 64)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @NotNull
    @Size(max = 128)
    public String getUri() {
        return this.uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    @Size(max = 65535)
    public String getFilters() {
        return this.filters;
    }

    public void setFilters(String filters) {
        this.filters = filters;
    }

    @Size(max = 65535)
    public String getPredicates() {
        return this.predicates;
    }

    public void setPredicates(String predicates) {
        this.predicates = predicates;
    }

    @Size(max = 65535)
    public String getMetadata() {
        return this.metadata;
    }

    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }

    public Integer getOrder() {
        return this.order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Boolean getDeleted() {
        return this.deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public Long getCreated() {
        return this.created;
    }

    public void setCreated(Long created) {
        this.created = created;
    }

    public Long getLastModified() {
        return this.lastModified;
    }

    public void setLastModified(Long lastModified) {
        this.lastModified = lastModified;
    }

    @Size(max = 64)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Size(max = 64)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RoutesEntity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(uri);
        sb.append(", ").append(filters);
        sb.append(", ").append(predicates);
        sb.append(", ").append(metadata);
        sb.append(", ").append(order);
        sb.append(", ").append(deleted);
        sb.append(", ").append(created);
        sb.append(", ").append(lastModified);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastModifiedBy);

        sb.append(")");
        return sb.toString();
    }
}
