/*
 * This file is generated by jOOQ.
 */
package com.motorfu.gateway.jooq.tables.records;


import com.motorfu.gateway.jooq.tables.RoutesTable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 网关路由
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutesRecord extends UpdatableRecordImpl<RoutesRecord> implements Record12<Long, String, String, String, String, String, Integer, Boolean, Long, Long, String, String> {

    private static final long serialVersionUID = -1546104075;

    /**
     * Setter for <code>gateway.routes.id</code>. 路由ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>gateway.routes.id</code>. 路由ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>gateway.routes.name</code>. 名称即routeId
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gateway.routes.name</code>. 名称即routeId
     */
    @Size(max = 64)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gateway.routes.uri</code>. 代理路径
     */
    public void setUri(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gateway.routes.uri</code>. 代理路径
     */
    @NotNull
    @Size(max = 128)
    public String getUri() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gateway.routes.filters</code>. 对应RouteDefinition类中的filters
     */
    public void setFilters(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gateway.routes.filters</code>. 对应RouteDefinition类中的filters
     */
    @Size(max = 65535)
    public String getFilters() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gateway.routes.predicates</code>. 对应RouteDefinition类中的predicates
     */
    public void setPredicates(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gateway.routes.predicates</code>. 对应RouteDefinition类中的predicates
     */
    @Size(max = 65535)
    public String getPredicates() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gateway.routes.metadata</code>. 对应RouteDefinition类中的metadata
     */
    public void setMetadata(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gateway.routes.metadata</code>. 对应RouteDefinition类中的metadata
     */
    @Size(max = 65535)
    public String getMetadata() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gateway.routes.order</code>. 顺序
     */
    public void setOrder(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>gateway.routes.order</code>. 顺序
     */
    public Integer getOrder() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>gateway.routes.deleted</code>. 是否删除
     */
    public void setDeleted(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>gateway.routes.deleted</code>. 是否删除
     */
    public Boolean getDeleted() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>gateway.routes.created</code>. 记录创建时间
     */
    public void setCreated(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>gateway.routes.created</code>. 记录创建时间
     */
    public Long getCreated() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>gateway.routes.last_modified</code>. 记录更新时间
     */
    public void setLastModified(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>gateway.routes.last_modified</code>. 记录更新时间
     */
    public Long getLastModified() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>gateway.routes.created_by</code>. 记录创建人
     */
    public void setCreatedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>gateway.routes.created_by</code>. 记录创建人
     */
    @Size(max = 64)
    public String getCreatedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>gateway.routes.last_modified_by</code>. 记录更新人
     */
    public void setLastModifiedBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>gateway.routes.last_modified_by</code>. 记录更新人
     */
    @Size(max = 64)
    public String getLastModifiedBy() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, String, String, Integer, Boolean, Long, Long, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, String, String, String, String, String, Integer, Boolean, Long, Long, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RoutesTable.ROUTES.ID;
    }

    @Override
    public Field<String> field2() {
        return RoutesTable.ROUTES.NAME;
    }

    @Override
    public Field<String> field3() {
        return RoutesTable.ROUTES.URI;
    }

    @Override
    public Field<String> field4() {
        return RoutesTable.ROUTES.FILTERS;
    }

    @Override
    public Field<String> field5() {
        return RoutesTable.ROUTES.PREDICATES;
    }

    @Override
    public Field<String> field6() {
        return RoutesTable.ROUTES.METADATA;
    }

    @Override
    public Field<Integer> field7() {
        return RoutesTable.ROUTES.ORDER;
    }

    @Override
    public Field<Boolean> field8() {
        return RoutesTable.ROUTES.DELETED;
    }

    @Override
    public Field<Long> field9() {
        return RoutesTable.ROUTES.CREATED;
    }

    @Override
    public Field<Long> field10() {
        return RoutesTable.ROUTES.LAST_MODIFIED;
    }

    @Override
    public Field<String> field11() {
        return RoutesTable.ROUTES.CREATED_BY;
    }

    @Override
    public Field<String> field12() {
        return RoutesTable.ROUTES.LAST_MODIFIED_BY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getUri();
    }

    @Override
    public String component4() {
        return getFilters();
    }

    @Override
    public String component5() {
        return getPredicates();
    }

    @Override
    public String component6() {
        return getMetadata();
    }

    @Override
    public Integer component7() {
        return getOrder();
    }

    @Override
    public Boolean component8() {
        return getDeleted();
    }

    @Override
    public Long component9() {
        return getCreated();
    }

    @Override
    public Long component10() {
        return getLastModified();
    }

    @Override
    public String component11() {
        return getCreatedBy();
    }

    @Override
    public String component12() {
        return getLastModifiedBy();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getUri();
    }

    @Override
    public String value4() {
        return getFilters();
    }

    @Override
    public String value5() {
        return getPredicates();
    }

    @Override
    public String value6() {
        return getMetadata();
    }

    @Override
    public Integer value7() {
        return getOrder();
    }

    @Override
    public Boolean value8() {
        return getDeleted();
    }

    @Override
    public Long value9() {
        return getCreated();
    }

    @Override
    public Long value10() {
        return getLastModified();
    }

    @Override
    public String value11() {
        return getCreatedBy();
    }

    @Override
    public String value12() {
        return getLastModifiedBy();
    }

    @Override
    public RoutesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RoutesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RoutesRecord value3(String value) {
        setUri(value);
        return this;
    }

    @Override
    public RoutesRecord value4(String value) {
        setFilters(value);
        return this;
    }

    @Override
    public RoutesRecord value5(String value) {
        setPredicates(value);
        return this;
    }

    @Override
    public RoutesRecord value6(String value) {
        setMetadata(value);
        return this;
    }

    @Override
    public RoutesRecord value7(Integer value) {
        setOrder(value);
        return this;
    }

    @Override
    public RoutesRecord value8(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public RoutesRecord value9(Long value) {
        setCreated(value);
        return this;
    }

    @Override
    public RoutesRecord value10(Long value) {
        setLastModified(value);
        return this;
    }

    @Override
    public RoutesRecord value11(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public RoutesRecord value12(String value) {
        setLastModifiedBy(value);
        return this;
    }

    @Override
    public RoutesRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Integer value7, Boolean value8, Long value9, Long value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoutesRecord
     */
    public RoutesRecord() {
        super(RoutesTable.ROUTES);
    }

    /**
     * Create a detached, initialised RoutesRecord
     */
    public RoutesRecord(Long id, String name, String uri, String filters, String predicates, String metadata, Integer order, Boolean deleted, Long created, Long lastModified, String createdBy, String lastModifiedBy) {
        super(RoutesTable.ROUTES);

        set(0, id);
        set(1, name);
        set(2, uri);
        set(3, filters);
        set(4, predicates);
        set(5, metadata);
        set(6, order);
        set(7, deleted);
        set(8, created);
        set(9, lastModified);
        set(10, createdBy);
        set(11, lastModifiedBy);
    }
}
