/*
 * This file is generated by jOOQ.
 */
package com.motorfu.gateway.jooq.routines;


import com.motorfu.gateway.jooq.GatewayTable;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddcolumnTable extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1351548711;

    /**
     * The parameter <code>gateway.addColumn.tn</code>.
     */
    public static final Parameter<String> TN = Internal.createParameter("tn", org.jooq.impl.SQLDataType.VARCHAR(64), false, false);

    /**
     * The parameter <code>gateway.addColumn.cn</code>.
     */
    public static final Parameter<String> CN = Internal.createParameter("cn", org.jooq.impl.SQLDataType.VARCHAR(64), false, false);

    /**
     * The parameter <code>gateway.addColumn.content</code>.
     */
    public static final Parameter<String> CONTENT = Internal.createParameter("content", org.jooq.impl.SQLDataType.VARCHAR(128), false, false);

    /**
     * Create a new routine call instance
     */
    public AddcolumnTable() {
        super("addColumn", GatewayTable.GATEWAY);

        addInParameter(TN);
        addInParameter(CN);
        addInParameter(CONTENT);
    }

    /**
     * Set the <code>tn</code> parameter IN value to the routine
     */
    public void setTn(String value) {
        setValue(TN, value);
    }

    /**
     * Set the <code>cn</code> parameter IN value to the routine
     */
    public void setCn(String value) {
        setValue(CN, value);
    }

    /**
     * Set the <code>content</code> parameter IN value to the routine
     */
    public void setContent(String value) {
        setValue(CONTENT, value);
    }
}
