spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8
    initialization-mode: ALWAYS
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jooq:
    sql-dialect: mysql

gateway:
  version: "@project.version@"