/*
 * This file is generated by jOOQ.
 */
package com.motorfu.gateway.jooq;


import com.motorfu.gateway.jooq.tables.RoutesTable;
import com.motorfu.gateway.jooq.tables.records.RoutesRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>gateway</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RoutesRecord, Long> IDENTITY_ROUTES = Identities0.IDENTITY_ROUTES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RoutesRecord> KEY_ROUTES_PRIMARY = UniqueKeys0.KEY_ROUTES_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RoutesRecord, Long> IDENTITY_ROUTES = Internal.createIdentity(RoutesTable.ROUTES, RoutesTable.ROUTES.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<RoutesRecord> KEY_ROUTES_PRIMARY = Internal.createUniqueKey(RoutesTable.ROUTES, "KEY_routes_PRIMARY", new TableField[] { RoutesTable.ROUTES.ID }, true);
    }
}
