/*
 * This file is generated by jOOQ.
 */
package com.motorfu.gateway.jooq;


import com.motorfu.gateway.jooq.tables.RoutesTable;


/**
 * Convenience access to all tables in gateway
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 网关路由
     */
    public static final RoutesTable ROUTES = RoutesTable.ROUTES;
}
